# Lab 00 - Becoming BFFs with Jupyter

In this Jupyter notebook, we will go through some basics of using Jupyter notebooks. These will be the medium which encompasses your lab notebook, data recording, and data analysis!

Note that we know that for many of you this will be your first encounter with Jupyter notebooks and with coding in general. It is perfectly normal if you feel some cognitive overload as we go through this notebook together with all the new information. Much of what we discuss today will be revisited in future pre-labs and labs, and we do not at all expect you to know perfectly how to do everything after today. This notebook will hopefully serve as a reference for using Jupyter notebooks that you can refer back to.

## Cells - Code and Markdown

The first thing we will introduce is the "base units" of the Jupyter notebook, known as cells. They come in two types; Code cells (where you can write and run Python) and Markdown cells (where you can write text, and also create headings and equations). The benefit of using a Jupyter notebook for these labs is that you can seamlessly alternate between Markdown and Code cells. In a generic PHYS 119 lab, we will have periods of notetaking when you are familiarizing yourself with the equipment for an experiment, coming up with a measurement plan, explaining your results and analysis, as well as planning and executing improvements. At other times, you will be using Python code to store data and perform analysis. A Jupyter notebook thus allows you to seamlessly transition between notetaking via formatted text (Markdown) and analysis (Python code).

This cell that you are currently reading is a markdown cell.

In [ ]:
# While this cell is a code cell.
x = 3.1415
y = 2.7
z = x + y

Cells can be added using the "+" button that you see in the top toolbar (in between the floppy disk (save) and scissor (cut) buttons). You can change the cell type using the dropdown menu in the same toolbar (in between the double play (rerun notebook) and clock (displaying differences from last checkpoint) buttons). 

## Editing and Running Markdown Cells

Markdown cells can be edited by double clicking them. They can be then run (to be converted into text form) by clicking the "play" button in the top toolbar, or by Shift + Return. You can run code cells in the exact same way!

As practice, try double clicking on this cell, and type in your favourite quote below!

" "

## Typefaces, Headings & Lists in Markdown

Within Markdown, we can do things like making text **bold** or *in italics* (or ***both***).

Headings can be created by Throwing "#" symbols in front of markdown text. The more #s you have in front of a heading, the smaller the heading it will be (e.g # Large Heading, ## Medium Heading, ### Small Heading). You can also compress the size of a notebook by hiding cells under a heading; you can hide/unhide by clicking the triangle to the left of any given heading.

### This is a small heading

You can make numbered lists in markdown:
1. First entry
2. Second entry
3. Third entry

Or unnumbered bullet points:
- A thing
- Another thing
- Yet another thing

both which may be useful for taking notes.

## Math in Markdown

A powerful part of Markdown is the ability to type mathematical expressions through a typesetting system known as $\LaTeX$. While we won't require any knowledge or proficiency with $\LaTeX$ in this course, it may be useful for formatting the various equations that we will come across when looking at various physical laws or formulas for calculating uncertainties.

If you want to type mathematical expressions "in-line", surround them with single $s. For example:

The mass-energy equivalence $E = mc^2$ is attributed to Albert Einstein.

If you want to type mathematical expressions as equations, surround them with double "$"s. For example:

Schrodinger's Equation describes the time evolution of a quantum system. It can be written as:

$$ i \hbar \frac{\partial}{\partial t} \lvert \psi \rangle = H \lvert \psi \rangle$$

"+", "-", and "=", and numbers/symbols can be typed in $\LaTeX$ as you would do normally. Some other commands that that may come in useful are below for your reference:

Multiplication:
$$A \cdot B \text{ or } A \times B$$

Division/Fractions:
$$\frac{A}{B}$$

Powers:
$$y^{1/3} = x^2$$

Roots:
$$\sqrt{2} \neq \sqrt[3]{2}$$

Sums:
$$y = \sum_{i=1}^N x_i$$

One can also type in Greek letters by typing the name of the Greek letter preceded by a backslash \. Some that may be encountered during the lab are $\sigma$, $\Delta$ and $\chi$. 

There is a whole world of markdown that we have not completely explored in this tutorial, but the curious can discover more here! https://www.markdownguide.org. A two-page cheatsheet for math typesetting with $\LaTeX$ can be found here http://tug.ctan.org/info/undergradmath/undergradmath.pdf.

## Editing and Running Code Cells

All the data taking, analysis, and display in this course will be done through Python. Like with $\LaTeX$, we will not expect extensive knowledge or proficiency in this course (but those curious can look forwards to PHYS 210!) However, we will want to become familiar enough to adapt and understand the provided code to accomplish the tasks for each lab.

Code cells can be edited by clicking and writing. They can be run just like markdown cells, by clicking the "play" button in the top toolbar, or by Shift + Return. This will run the python code in that cell.

In [ ]:
# This is a code cell.
# Python treats any lines with a "#" in front as a comment.
# So these lines will do nothing even if the cell is run.
x = 5  # You can also put comments after code.

## Arithmetic in python

Arithmetic in python with numbers works almost exactly like you would expect it!

In [ ]:
# Addition
1 + 2

3

In [ ]:
# Subtraction
2.5 - 1.2

1.3

In [ ]:
# Multiplication
2 * 3

6

In [ ]:
# Division
6 / 2

3.0

In [ ]:
# Exponentiation
2**3  # Note that ** = ^ in python

8

In [ ]:
# Roots
4**(1/2)

2.0

## Variables in python, printing

It will be useful to store and handle values symbolically (instead of just working with individual numbers all the time). To this end, we introduce variables. The cell below can be run to set the value of the variable "x" to be 7. In python, the "=" symbol is used as an assignment operator, rather than a checking if two things are equal (confusingly, that task is done by a double equals sign "=="... but this will not be necessary for this course!)

In [ ]:
x = 7

This stored value now persists across cells, so I can use this in future cells:

In [ ]:
x

7

However, sometimes I want to see the value of something not just at the end of the cell (As we have been doing now) but at some intermediate point in the cell. For this, the print function is very useful. Try running the cell below, where we assign some values, and along the way print the value of a to see what it is:

In [ ]:
a = 1
print(a)
b = 2

1


Note that we can also do arithmetic operations on variables. For example, what do you expect the value of c to be below? Try printing c to see if your guess matches up with what you expect.

In [ ]:
c = a + b
# Try printing out c in the line below.


## Importing libraries

Often, there are additional functionalities that base python does not provide, but are extremely useful. In order to access these, we have to import them. A common library we will be using in this course (and one of the most common libraries used in general) is numPy (numerical python). We will also be using a data entry program designed for this course to take data. Run the cell below to import these libraries:

In [2]:
import numpy as np
import data_entry

ModuleNotFoundError: ignored

Now these libraries are accessible in any cell of this notebook until you quit out of it! Note that for future notebooks, we will import libraries at the very beginning of the notebook (and then not worry about them again).

## Arrays and Array Operations

In experiments, we often work with datasets rather than individual points of data; it is therefore going to be useful to become acquainted with a datastructure known as an array. An array holds multiple entries of data. Running the cell below defines two arrays, ``first_vec`` and ``second_vec``.

In [3]:
first_vec = np.array([2, 4, 6])
second_vec = np.array([3, 5, 7])

Elements of an array can be accessed by `array[position in array]`. However, note that the position/indexing of arrays in python starts with 0, rather than 1.

In [4]:
first_element = first_vec[0]  # The first element of a python array is indexed by 0, not 1.
print(first_element)

second_element = first_vec[1]  # 1 then gives you the second element of the array.
print(second_element)

2
4


Arrays can be termwise added, multiplied, subtracted, divided, and exponentiated.

In [ ]:
# Termwise addition
sum_vec = first_vec + second_vec
sum_vec

array([5, 7, 9])

In [ ]:
# Termwise subtraction
diff_vec = first_vec - second_vec
diff_vec

array([-3, -3, -3])

In [ ]:
# Termwise multiplication
mult_vec = first_vec * second_vec
mult_vec

array([ 4, 10, 18])

In [ ]:
# Termwise division
div_vec = first_vec/second_vec
div_vec

array([0.25, 0.4 , 0.5 ])

In [ ]:
# Termwise exponentiation
exp_vec = first_vec**(1/2)
exp_vec

array([1.        , 1.41421356, 1.73205081])

One can obtain the length of an array using the `len` function:

In [ ]:
length = len(first_vec)
print(length)

3


One can also sum over all elements in the array using the `np.sum` function:

In [ ]:
sum_of_elements = np.sum(first_vec)
sum_of_elements

6

## Data Entry

In this course, we will be using the `data_entry` library to record data from experiments. Running the below cell will bring up an example data table using this library (in particular, for an experiment that measured the gravitational force for varying masses).

In [ ]:
de = data_entry.sheet("lab00_example")

Sheet name: lab00_example.csv


The first row of a table holds the variable names (e.g. M for mass, F for force). The second row will hold the units for the variables (e.g. kg (kilograms) for mass, N (Newtons) for force). Then, the data table can be filled out using the columns. If more rows are needed for additional data points, you can click `Add Row`. If more columns are needed for additional variables, you can click `Add Column`. The data table can be edited by clicking on the cell you want to edit and filling it in. Finally, one functionality that will be very useful later on will be to do operations on our data to process and analyze it. To this end, the `Generate Vectors` button will generate arrays/vectors from the columns of the data table. These arrays/vectors can then be processed through the array operations discussed above.

The basic process for data recording and analysis in the lab is as follows:
1. Conduct a measurement and record the results using `data_entry`.
2. Use `Generate Vectors` to convert the data in the `data_entry` table into Python arrays/vectors.
3. Process the data by manipulating the data arrays in code.
4. Display the data.
5. Analyze/discuss the results.

Let's go through a mock trial of what this would look like below!

## A mock runthrough

Below, we have the same data table as above. Suppose we conducted another measurement, where we measured the $M = 2.9 \text{ kg}$ mass to exert a gravitational force of $F = 28.6 \text{ N}$. Let's add this to the below data table!

In [ ]:
de = data_entry.sheet("lab00_example")

Sheet name: lab00_example.csv


Now, let's generate arrays/vectors of the data by clicking the `Generate Vectors` button.

Next, we want to extract the value of the gravitational acceleration $g$, from $F = mg$. Try this by creating a new vector of the Force divided by the mass, in the code cell below.

In [ ]:
# Replace the ??s below to calculate an array/vector for g!
v_g = ??

SyntaxError: invalid syntax (2419045345.py, line 2)

In later labs we will display the data through plots, but for today, let's just display the processed data by printing the $g$ vector.

In [ ]:
# Below, print out v_g


Finally, in this cell, comment on any observations about the "measurement" of the gravitational constant you just conducted.

(Replace with some of your personal comments)