# Lab 00 - Becoming BFFs with Jupyter

In this Jupyter notebook, we will go through some basics of using Jupyter notebooks.

## Cells - Code and Markdown

The first thing we will introduce is the unit block of the Jupyter notebook. These are what is known as "cells". They come in two types; code cells (where you can write and run Python) and markdown cells (where you can write text, and also create headings and equations). This cell is a markdown cell.

In [1]:
# While this cell is a code cell.
x = 3.1415
y = 2.7
z = x + y

Cells can be added using the "+" button that you see in the top toolbar. You can change the cell type using the dropdown menu (to the left of the clock symbol).

## Editing and Running Markdown Cells

Markdown cells can be edited by double clicking them. They can be then run (to be converted into text form) by clicking the "play" button in the top toolbar, or by Shift + Return. Actually, you can run code cells in the exact same way.

Try double clicking on this cell, and type in your favourite quote below!

" "

## Headings in Markdown

Headings can be created by Throwing "#" symbols in front of markdown text. The more #s you have in front of a heading, the smaller the heading it will be (e.g # Large Heading, ## Medium Heading, ### Small Heading).

### Small Heading

## Math in Markdown

A powerful part of Markdown is the ability to type mathematical expressions through a typesetting system known as $\LaTeX$. While we won't require any knowledge or proficiency with $\LaTeX$ in this course, it can be useful to make your expressions look nice.

If you want to type mathematical expressions "in-line", surround them with single "$"s. For example:

The mass-energy equivalence $E = mc^2$ is attributed to Albert Einstein.

If you want to type mathematical expressions as equations, surround them with double "$"s. For example:

Schrodinger's Equation describes the time evolution of a quantum system. It can be written as:

$$ i \hbar \frac{\partial}{\partial t} \lvert \psi \rangle = H \lvert \psi \rangle$$

There is a whole world of markdown too large to be covered in this tutorial, but the curious can discover more here! https://www.markdownguide.org

## Running code cells, comments

Code cells can be edited by clicking and writing. They can be run just like markdown cells, by clicking the "play" button in the top toolbar, or by Shift + Return. This will run the python code in that cell.

In [ ]:
# This is (again) a code cell.
# Python treats any lines with a "#" in front as a comment.
# So these lines will do nothing even if the cell is run.

## Arithmetic in python

Arithmetic in python works almost exactly like you would expect it!

In [2]:
# Addition
1 + 2

3

In [6]:
# Subtraction
2.5 - 1.2

1.3

In [4]:
# Multiplication
2 * 3

6

In [5]:
# Division
6 / 2

3.0

In [8]:
# Exponentiation
2**3  # Note that ** = ^ in python

8

In [10]:
# Roots
4**(1/2)

2.0

## Variables in python, printing

It will be useful to store and handle values symbolically (instead of just working with individual numbers all the time). To this end, we introduce variables. The cell below can be run to set the value of the variable "x" to be 7. In python, the "=" symbol is used as an assignment operator, rather than a checking if two things are equal (confusingly, that task is done by a double equals sign "=="... but this will not be necessary for this course!)

In [9]:
x = 7

This stored value now persists across cells, so I can use this in future cells:

In [11]:
x

7

However, sometimes I want to see the value of something not just at the end of the cell (As we have been doing now) but at some intermediate point in the cell. For this, the print function is very useful. Try running the cell below, where we assign some values, and along the way print the value of a to see what it is:

In [13]:
a = 1
print(a)
b = 2

1


Note that we can also do arithmetic operations on variables. For example, what do you expect the value of c to be below? Try printing c to see if your guess matches up with what you expect.

In [15]:
c = a + b
# Try printing out c in the line below.


## Importing libraries

Often, there are additional functionalities that base python does not provide, but are extremely useful. In order to access these, we have to import them. A common library we will be using in this course (and one of the most common libraries used in general) is numPy (numerical python). We will also be using a data entry program designed for this course to take data. Run the cell below to import these libraries:

In [2]:
import numpy as np
import data_entry

Now these libraries are forever accessible until you quit this notebook! Note that for future notebooks, we will import libraries at the very beginning of the notebook (and then not worry about them again).

## Arrays and Array Operations

In experiments, we often work with datasets rather than individual points of data; it is therefore going to be useful to become acquainted with a datastructure known as an array. An array holds multiple entries of data. Running the cell below defines two arrays, ``first_vec`` and ``second_vec``.

In [3]:
first_vec = np.array([2, 4, 6])
second_vec = np.array([3, 5, 7])

Elements of an array can be accessed by `array[position in array]`. However, note that the position/indexing of arrays in python starts with 0, rather than 1.

In [5]:
first_element = first_vec[0]
print(first_element)

second_element = first_vec[1]
print(second_element)

1
2


Arrays can be termwise added, multiplied, subtracted, divided, and exponentiated.

In [6]:
# Termwise addition
sum_vec = first_vec + second_vec
sum_vec

array([5, 7, 9])

In [7]:
# Termwise subtraction
diff_vec = first_vec - second_vec
diff_vec

array([-3, -3, -3])

In [8]:
# Termwise multiplication
mult_vec = first_vec * second_vec
mult_vec

array([ 4, 10, 18])

In [10]:
# Termwise division
div_vec = first_vec/second_vec
div_vec

array([0.25, 0.4 , 0.5 ])

In [11]:
# Termwise exponentiation
exp_vec = first_vec**(1/2)
exp_vec

array([1.        , 1.41421356, 1.73205081])

One can obtain the length of an array using the `len` function:

In [12]:
length = len(first_vec)
print(length)

3


One can also sum over all elements in the array using the `np.sum` function:

In [13]:
sum_of_elements = np.sum(first_vec)
sum_of_elements

6

## Data Entry

In this course, we will be using the `data_entry` library to record data from experiments. Running the below cell will bring up an example data table using this library.

**Might be good to remove the uncertainty columns for now - They won't have seen this before**

In [15]:
de = data_entry.sheet("lab00_example")

Sheet name: lab00_example.csv


The first row of a table holds the variable names (e.g. M for mass, u[M] for the uncertainty in mass, E for energy etc.). The second row will hold the units for the variables (e.g. kg (kilograms) for mass, J (Joules) for energy). Then, the data table can be filled out using the columns. If more rows are needed for additional data points, you can click `Add Row`. If more columns are needed for additional variables, you can click `Add Column`. The data table can be edited by clicking on the cell you want to edit and filling it in. Try playing around with the example data table above to get a feel for how it works!

Finally, one functionality that will be very useful later on will be to do operations on our data to process and analyze it. To this end, the `Generate Vectors` button will generate arrays/vectors from the columns of the data table. These arrays/vectors can then be processed through the array operations discussed above.